### PR TITLE
UI Kit v2

### PR DESCRIPTION
**Pull request by GabrielCousin**
**List of breaking changes :**
- Color set
- Vertical unit: 5px instead of 4.5px
- Removed `.Tabs--vertical`
- New markup on `.Tabs` (neither using `<ul>` anymore, nor `.Tab-item`, nor `.Tab-link`)
- Removed `.Btn--circle`
- Renamed `.Btn-expandContainer` into `.BtnContainer`
- All disabled btns share the same layout
- `.Dropdown-toggle` has style
- Default links font-weight is regular
- BtnGroup: different layout, should be used as filter buttons
- Btn are using `display: inline-flex;`
- Icons: various renaming and deletion 
- Remove border-bottom on `.Table-head` since must be wrapped into `</tr>`

### CODE REVIEW

**Comment by GabrielCousin** [comment]
(WIP)

**Comment by GabrielCousin** [comment]
- [x] Update icons
- [x] Complete documentation
- [x] Fix input-group
- [ ] Update tests

**Comment by ugogo** [comment]
- [ ] Fix visual tests :trollface:

**Comment by GabrielCousin** [comment]
Renaming zone:

alert->warningSign
add -> pelletAdd
arrowBack -> arrowLeft
arrowNext -> arrowRight
bulletDay -> donutDot
diagram -> pieDiagram
linkDropbox -> dropboxLink
linkGoogle -> googleDriveLink
meetingList -> list
note -> dot
openQuestion -> comment
privateNote -> private
public -> door
title--1 -> heading1
title--2 -> heading2
themes -> folder
vote -> barDiagram
wiFi -> wifi

Deletion zone:
actionItem
agendaItem
checked
checkedActionItem
decision
groupRounded
openIssue
optionsRounded
recurring
resetRounded
statsRounded
typeAdd
typeParagraph
voice

Added icons:

alert (rounded)
bulb
company
copy
dumbell
deleteUser
dashboard
dropbox
flag
googleDrive
insights
integrations
listPlain
projector
quote
rss
summary
timeline
triangleLeft
triangleRight
warning
youtube

**Comment by ugogo** [comment]
awesome work so far 🙌🏼

**Comment by ugogo** [comment]
🔥

**Pull request merged**
