### PR TITLE
Various improvements

### PR DESCRIPTION
**Pull request by ugogo**
- [x] #87
- [x] #97
- [x] #99
- [x] #100
- [x] #101

### CODE REVIEW

**Comment by AlexandreBroudin** [comment]
:+1: j'ai tout en regardé en détail, mais ça me semble valide

**Comment by GabrielCousin** [comment]
:sheep:

**Comment by ugogo** [comment]
Good for you w/ the last commit @AlexandreBroudin @GabrielCousin?

**Comment by AlexandreBroudin** [comment]
Ok, just a bit confused about fieldset name

**Comment by ugogo** [comment]
Well, `.Fieldset` is for... a fieldset 😅

**Pull request merged**
