### PR TITLE
Input group select & input addon

### PR DESCRIPTION
**Pull request by AlexandreBroudin**

### CODE REVIEW

**Comment by GabrielCousin** [comment]
Don't forget to build the CSS file

**Comment by GabrielCousin** [comment]
image

**Comment by ugogo** [comment]
capture d ecran 2016-01-04 a 14 41 35

**Comment by GabrielCousin** [comment]
giphy

**Comment by GabrielCousin** [comment]
Merge #210 and then remove the 2 first commits.

**Comment by GabrielCousin** [comment]
Don't forget to commit `tapestry.css`

**Comment by GabrielCousin** [comment]
I squashed some commits. OK for you @ugogo ?

**Comment by ugogo** [comment]
Remove the last example and :shipit:

**Pull request merged**
