### PR TITLE
Node update

### PR DESCRIPTION
**Pull request by GabrielCousin**
- `nvm install 4.2.1 && nvm use 4.2.1` or install Node 4.2.1
- `rm -rf node_modules`
- `npm install`
- :shipit: ?

### CODE REVIEW

**Comment by ugogo** [comment]
:shipit: ?

**Comment by GabrielCousin** [comment]
Needs to be tested with Node 5.1 #lacommunication

**Comment by ugogo** [comment]
I'm on it.

**Comment by ugogo** [comment]
All's good :+1:

**Pull request merged**
