### PR TITLE
Component modal

### PR DESCRIPTION
**Pull request by GabrielCousin**

### CODE REVIEW

**Comment by AlexandreBroudin** [comment]
:+1:

**Comment by ugogo** [comment]
**Overlay**
- [ ] Animation only work when "fade in", not on "fade out"

**Modal**
- [x] Animation should not be on `top`, but with a `translateY`
- [x] Merge `_types.scss` into `_base.scss` ?
- [x] For me, there is no reason to have `.Modal-contentItem` because it's more a `List` component
- [x] Are `Modal-content--message` and `Modal-content--menu` really useful?
- [x] `body` shouldn't scroll when a modal is open
- [x] `flex` is only useful for `Modal--expand`
- [x] `ModalHeader-title` -> `Modal-title`
- [x] padding on `.ModalHeader-button` is useless since it's the default `.Btn` padding
- [x] margin on `.ModalHeader-title` should be replace with a `line-height`. If we change node to `<h1>`, it's broken.

**Comment by GabrielCousin** [comment]
Please review again <3
Overlay is not part of the PR.

**Comment by ugogo** [comment]
Should be :+1:

**Pull request merged**
