### PR TITLE
Icons | add spin animation

### PR DESCRIPTION
**Pull request by GabrielCousin**
I know we delete and re-add this several times. Since we are now sharing icons between Wisembly and Solid, it would be a good thing to share icon-animations too.

### CODE REVIEW

**Comment by AlexandreBroudin** [comment]
So we should make something more generic that could be applied by JavaScript as well, like `is-rotating` or maybe `a-rotate`

**Comment by GabrielCousin** [comment]
Sure. Then, why not using `is-loading` which makes more sense in a JS point of view, where as `is-rotating` is quite visual?

**Comment by AlexandreBroudin** [comment]
`is-loading` can be associate with anything, loading bar, spinner, etc…
We will have to prepare default behaviours, like `.Icon.is-loading { }` or `.Meter.is-loading { }` but reading it, it doesn't make lot of sens, semantically speaking. We are not loading an icon nor a meter we are loading a view or a set of views.

**Comment by GabrielCousin** [comment]
Agreed. I will update it

**Comment by ugogo** [comment]
What about `is-spinning` ?

**Comment by GabrielCousin** [comment]
Yolo! I will merge when you are ready. I will bump a new version tomorrow, there are some old icons to remove.

**Comment by AlexandreBroudin** [comment]
:+1:

**Comment by ugogo** [comment]
:shipit:

**Pull request merged**
