### PR TITLE
Notifications | update layout

### PR DESCRIPTION
**Pull request by GabrielCousin**
- [x] Only use box-shadow on .Notification--fixed
- [x] Default .Notification has neutral background
- [x] Create .Notification--primary

### CODE REVIEW

**Comment by AlexandreBroudin** [comment]
Should we add the ability to close this notification ?
eg: a cross on the top right of it

**Comment by GabrielCousin** [comment]
It would definitively be a great improvement but must comes with its proper script as we did with dropdowns. Otherwise the work is still done at 50%. I will create some JS-focused issues

**Comment by AlexandreBroudin** [comment]
Banjo

**Comment by ugogo** [comment]
:baby_chick:

**Comment by AlexandreBroudin** [comment]
:shipit:

**Pull request merged**
