### PR TITLE
Improve lists

### PR DESCRIPTION
**Pull request by GabrielCousin**
- Better at handling borders
- Take benefit of flex instead of absolute positionning
- Add headers
- List-item is more generic and flexible

### CODE REVIEW

**Comment by GabrielCousin** [comment]
- [x] Documentation && vars
- [x] Update Modal with list

**Comment by ugogo** [comment]
IMO it's a bit weird to have the `header`

``` html
<header class="List-header">… </header>
```

then the list

``` html
<ul class="List">
    <li class="List-item">…</li>
    …
</ul>
```

with those classes I think.

---

What about something like this?

``` html
<div class="List">
    <header>…</header>
    <ul class="List-content">…</ul>
</div>
```

Here the `List-header` is implicit with `header`, and we could target it with `.List > header`, but it doesn't suit our coding rules… but that's a detail

**Comment by AlexandreBroudin** [comment]
If you want something semantically correct

``` html
<section>
  <header class="List-header">
    <h3 class="List-title">Header Title</h3>
    <p class="List-description">My description</p>
  </header>
  <ul class="List">
    <li class="List-item">Foo</li>
    <li class="List-item">Bar</li>
    <li class="List-item">Baz</li>
  </ul>
</section>
```

But it's wrong as a BEM component.
So maybe something like this (same as @ugogo example 👯 )

``` html
<section class="List">
  <header class="List-header">
    <h3 class="List-title">Header Title</h3>
    <p class="List-description">My description</p>
  </header>
  <ul class="List-content">
    <li class="List-item">Foo</li>
    <li class="List-item">Bar</li>
    <li class="List-item">Baz</li>
  </ul>
</section>
```

**Comment by GabrielCousin** [comment]
Great idea :) #grosseschön

**Comment by ugogo** [comment]
I don't think a `header` **has** to be wrapped by a `section`.
But LGTM 👍

**Comment by GabrielCousin** [comment]
Thanks for both feedbacks, I just pushed them.
I kept `<div>`, but `<section>` are usable too.
We might use both of them in documentation.

@ugogo I changed markup `<header>` / `<footer>` on Modals (branch: `ui-kit-v2`). It was already applied on Panels.

**Comment by GabrielCousin** [comment]
Should I merge into `ui-kit-v2` ?

**Comment by ugogo** [comment]
Well, why not.
This will be a huge step for v1 👍

**Comment by GabrielCousin** [comment]
Merge has been postponed to 1.x.0

**Pull request merged**
