### PR TITLE
Inputs imps

### PR DESCRIPTION
**Pull request by AlexandreBroudin**

### CODE REVIEW

**Comment by GabrielCousin** [comment]
- [x] Merge/cherry-pick/improve `.Input.has-icon…` #215
- [x] Update checkboxes
- [x] Update radios
- [x] Update `.Dropdown-select` / select

**Comment by GabrielCousin** [comment]
Please review @ugogo && @AlexandreBroudin

**Comment by AlexandreBroudin** [comment]
:shipit:

**Comment by ugogo** [comment]
:ship:

**Pull request merged**
