### PR TITLE
Variabilize

### PR DESCRIPTION
**Pull request by ugogo**
**To fix**
- `Btn--outline` (`padding: rb(2) rb(4)`) -> size is not dynamic

**Todo**
- [x] Specify for each component what var is needed
- [x] Update "Settings and vars can be overidden." in /getting-started

### CODE REVIEW

**Comment by GabrielCousin** [comment]
- [x] Pellet
- [x] Tooltip
- [x] Table

**Comment by GabrielCousin** [comment]
Will write documentation next week and let's get the money.

**Comment by GabrielCousin** [comment]
shipit-3
REVIEW NEEDED

**Comment by GabrielCousin** [comment]
Currently finishing inputs.
- [x] Tabs
- [x] Popovers

**Comment by GabrielCousin** [comment]
Ultimate check please?
image

**Comment by ugogo** [comment]
Sometimes variables are at the bottom of the page (input, grid, …) ?

**Comment by GabrielCousin** [comment]
Let's merge?

**Comment by ugogo** [comment]
:facepunch:

**Pull request merged**
