### PR TITLE
Webpack imports

### PR DESCRIPTION
**Pull request by GabrielCousin**
#330

### CODE REVIEW

**Comment by ugogo** [comment]
Mh, not a big fan of doing stuff for a specific tool
Since `$input-valid-bg-path` is overridable, I guess the user only have to update this var in his own `.scss`, wdyt?

`$input-valid-bg-path: "/src/svg/backgrounds/inputBg--valid.svg" !default;`

**Comment by GabrielCousin** [comment]
We already do this with `$f-path`. Overriding $vars is not really working well in this case.
Supporting Webpack is a great thing IMO since it moves automatically needed files. You don't have to add an extra package to base64 encode stuff for example

**Comment by ugogo** [comment]
I'm not saying that we shouldn't support Webpack, I'm saying we should work with every workable env. If we can't, we should be flexible enough to allow that.
What I'm against, is doing specific setup for a specific env.
At the end, we can have a config file with a var for each tool, and it's gonna be a real mess

**Comment by GabrielCousin** [comment]
@ugogo have you changed your mind? 🏩

**Comment by ugogo** [comment]
Okayyyyy

**Pull request merged**
