### PR TITLE
Typography | Add h6 layout

### PR DESCRIPTION
**Pull request by GabrielCousin**
#225

### CODE REVIEW

**Comment by GabrielCousin** [comment]
I didn't do this. I just reorganized it. Some margin properties were overriding themselves

**Comment by ugogo** [comment]
Well

https://github.com/Wisembly/tapestry/commit/93ff6cde4e51084ecdd7adb9c181053d3ca49cc2#diff-30ccc8d47698496a42a230cebec66a77L501

https://github.com/Wisembly/tapestry/commit/93ff6cde4e51084ecdd7adb9c181053d3ca49cc2#diff-5a669114f7d32173ac17f90b2cbf5052L30

**Comment by GabrielCousin** [comment]
still here, expand it : https://github.com/Wisembly/tapestry/commit/93ff6cde4e51084ecdd7adb9c181053d3ca49cc2#diff-30ccc8d47698496a42a230cebec66a77R532

**Comment by ugogo** [comment]
Ah 😅, my bad sorry.
:shipit:

**Pull request merged**
